source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '3.0.0'
gem 'mysql', '2.8.1'
gem 'haml'
gem 'json'
gem 'oauth2', '0.0.8'
gem 'addressable', '2.1.2'
gem 'faraday', '0.4.5'
gem 'authlogic', :git => 'git://github.com/odorcicd/authlogic.git', :branch => 'rails3'
gem 'ruby-debug'
gem 'rspec'