development:
  adapter: mysql
  database: bringingwhat_development
  username: root
  password:
  timeout: 5000
  
test:
  adapter: mysql
  database: bringingwhat_test
  username: root
  password: 
  timeout: 5000