development:
  adapter: mysql
  database: bringingwhat_development
  username: root
  password:
  host: localhost

  
test:
  adapter: mysql
  database: bringingwhat_test
  username: root
  password: 
  host: localhost
  